# Generated by Django 4.1.2 on 2022-10-19 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=100)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('description', models.CharField(max_length=1000)),
                ('venue', models.CharField(max_length=100)),
                ('status', models.BooleanField(default='1', editable=False)),
            ],
            options={
                'db_table': 'fifa_event_table',
            },
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('group', models.CharField(max_length=1)),
                ('name', models.CharField(max_length=100)),
                ('coach', models.CharField(max_length=100)),
                ('status', models.BooleanField(default='1', editable=False)),
            ],
            options={
                'db_table': 'fifa_team_table',
            },
        ),
    ]
