# Generated by Django 4.1.2 on 2022-10-31 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('eventId', models.AutoField(primary_key=True, serialize=False)),
                ('eventName', models.CharField(max_length=100)),
                ('startDate', models.DateField(null=True)),
                ('endDate', models.DateField(null=True)),
                ('description', models.CharField(max_length=1000)),
                ('venue', models.CharField(max_length=100)),
                ('eStatus', models.BooleanField(default='1', editable=False)),
            ],
            options={
                'db_table': 'fifa_event_table',
            },
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('teamId', models.AutoField(primary_key=True, serialize=False)),
                ('group', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=100)),
                ('coach', models.CharField(max_length=100)),
                ('tStatus', models.BooleanField(default='1', editable=False)),
            ],
            options={
                'db_table': 'fifa_team_table',
            },
        ),
        migrations.CreateModel(
            name='UserQuestions',
            fields=[
                ('qId', models.AutoField(primary_key=True, serialize=False)),
                ('matchId', models.IntegerField(null=True)),
                ('question', models.CharField(max_length=1000)),
                ('op1', models.CharField(max_length=100, null=True)),
                ('op2', models.CharField(max_length=100, null=True)),
                ('op3', models.CharField(max_length=100, null=True)),
                ('point', models.IntegerField(null=True)),
                ('qType', models.CharField(max_length=8, null=True)),
                ('qStatus', models.BooleanField(default='1', editable=False)),
            ],
            options={
                'db_table': 'fifa_quizquestions_table',
            },
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('eventId', models.IntegerField(default='1', editable=False)),
                ('matchId', models.AutoField(primary_key=True, serialize=False)),
                ('startTime', models.DateTimeField(null=True)),
                ('venue', models.CharField(max_length=100)),
                ('resultId', models.CharField(default='NA', max_length=100, null=True)),
                ('published', models.BooleanField(default='1')),
                ('fStatus', models.BooleanField(default='1', editable=False)),
                ('status', models.BooleanField(default='1')),
                ('teamA', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teamA', to='fifa22_app.teams')),
                ('teamB', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teamB', to='fifa22_app.teams')),
            ],
            options={
                'db_table': 'fifa_fixture_table',
            },
        ),
    ]
