# Generated by Django 4.1.2 on 2022-10-25 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=100)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('description', models.CharField(max_length=1000)),
                ('venue', models.CharField(max_length=100)),
                ('e_status', models.BooleanField(default='1', editable=False)),
            ],
            options={
                'db_table': 'fifa_event_table',
            },
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('event_id', models.IntegerField(default='1', editable=False)),
                ('match_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('team_A', models.CharField(max_length=100)),
                ('team_B', models.CharField(max_length=100)),
                ('venue', models.CharField(max_length=100)),
                ('result_id', models.CharField(max_length=100, null=True)),
                ('f_status', models.BooleanField(default='1', editable=False)),
            ],
            options={
                'db_table': 'fifa_fixture_table',
            },
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('group', models.CharField(max_length=1)),
                ('name', models.CharField(max_length=100)),
                ('coach', models.CharField(max_length=100)),
                ('t_status', models.BooleanField(default='1', editable=False)),
            ],
            options={
                'db_table': 'fifa_team_table',
            },
        ),
        migrations.CreateModel(
            name='UserQuestions',
            fields=[
                ('Q_id', models.AutoField(primary_key=True, serialize=False)),
                ('match_id', models.IntegerField(null=True)),
                ('question', models.CharField(max_length=1000)),
                ('op1', models.CharField(max_length=100, null=True)),
                ('op2', models.CharField(max_length=100, null=True)),
                ('op3', models.CharField(max_length=100, null=True)),
                ('op4', models.CharField(max_length=100, null=True)),
                ('q_type', models.CharField(choices=[('T', 'Team'), ('P', 'Player'), ('G', 'General')], default='G', max_length=1)),
                ('q_status', models.BooleanField(default='1', editable=False)),
            ],
            options={
                'db_table': 'fifa_quizquestions_table',
            },
        ),
    ]
