# Generated by Django 4.1.2 on 2022-10-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifa22_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('event_id', models.IntegerField(default='1', editable=False)),
                ('match_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('Team_A', models.IntegerField()),
                ('Team_B', models.IntegerField()),
                ('Venue', models.CharField(max_length=100)),
                ('Result_id', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'fifa_fixture_table',
            },
        ),
    ]
