# Generated by Django 4.1.2 on 2022-11-01 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifa22_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='temp',
            fields=[
                ('tId', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=10)),
                ('grade', models.CharField(max_length=2, null=True)),
                ('point', models.IntegerField(default='0')),
                ('totpoints', models.IntegerField(default='0')),
            ],
            options={
                'db_table': 'aaaaaaq',
            },
        ),
    ]
