# Generated by Django 4.1.2 on 2022-10-19 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifa22_app', '0002_fixture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='Team_A',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='Team_B',
            field=models.CharField(max_length=100),
        ),
    ]
