# Generated by Django 4.1.2 on 2022-10-27 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fifa22_app', '0003_userquestions_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userquestions',
            name='op4',
        ),
    ]
