# Generated by Django 4.1.2 on 2022-10-27 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifa22_app', '0004_remove_userquestions_op4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquestions',
            name='q_type',
            field=models.CharField(choices=[('T', 'Team'), ('P', 'Player'), ('G', 'General')], default='G', max_length=8),
        ),
    ]
