# Generated by Django 4.1.2 on 2022-10-27 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifa22_app', '0005_alter_userquestions_q_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquestions',
            name='q_type',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
